# Copyright (c) Meta Platforms, Inc. and affiliates.

"""
CUTracer Python SDK

This package provides tools for validating, parsing, and analyzing
CUDA trace data generated by CUTracer.
"""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("cutracer")
except PackageNotFoundError:
    __version__ = "0+unknown"  # Development mode or not installed

from cutracer.validation import (
    compare_trace_formats,
    validate_json_trace,
    validate_text_trace,
)

__all__ = [
    "__version__",
    "validate_json_trace",
    "validate_text_trace",
    "compare_trace_formats",
]
