# Copyright (c) Meta Platforms, Inc. and affiliates.

"""
CUTracer Python SDK

This package provides tools for validating, parsing, and analyzing
CUDA trace data generated by CUTracer.
"""

__version__ = "0.1.0"

from cutracer.validation import (
    validate_json_trace,
    validate_text_trace,
    compare_trace_formats,
)

__all__ = [
    "__version__",
    "validate_json_trace",
    "validate_text_trace",
    "compare_trace_formats",
]
