# Copyright (c) Meta Platforms, Inc. and affiliates.

"""
Mini-reproducer for Hopper TLX warp-specialized GEMM kernel hang.

Kernel: matmul_kernel_tlx_ws
Target: sm90 (H100)
Configuration: 65536x1024x1024 fp16 GEMM (BM=128, BN=256, BK=64, NUM_STAGES=4)

Generated by TritonParse then manually simplified.

To run:
1. setup TLX env:
https://github.com/facebookexperimental/triton/tree/main/test
2. `python hopper_matmul_kernel_tlx_ws.py`
"""

import torch
import triton
import triton.language as tl
import triton.language.extra.tlx as tlx
from triton.tools.tensor_descriptor import TensorDescriptor


@triton.jit
def matmul_kernel_tlx_ws(
    a_desc,
    b_desc,
    c_desc,  #
    M,
    N,
    K,  #
    BM: tl.constexpr,  #
    BN: tl.constexpr,  #
    BK: tl.constexpr,  #
    GROUP_SIZE_M: tl.constexpr,  #
    NUM_STAGES: tl.constexpr,  #
    NUM_MMA_WARPS: tl.constexpr,  #
    NUM_MMA_GROUPS: tl.constexpr,  #
    EPILOGUE_SUBTILE: tl.constexpr,  #
):
    # Descriptor
    BLOCK_M_SPLIT: tl.constexpr = BM // NUM_MMA_GROUPS

    # Need NUM_STAGES sets of SMEM buffers for A and B
    # where each set contains two for A and one for B.
    # Split A into two in M-dimension to have two consumer tasks for wgmma
    a = tlx.local_alloc(
        (BLOCK_M_SPLIT, BK), tlx.dtype_of(a_desc), NUM_STAGES * NUM_MMA_GROUPS
    )
    b = tlx.local_alloc((BK, BN), tlx.dtype_of(b_desc), NUM_STAGES)

    # Need NUM_STAGES sets of mbarriers for A and B
    # where each set contains two for A and one for B.
    # Do the above for both empty states and full states respectively.
    bars_empty_a = tlx.alloc_barriers(
        num_barriers=NUM_STAGES * NUM_MMA_GROUPS, arrive_count=1
    )
    bars_full_a = tlx.alloc_barriers(
        num_barriers=NUM_STAGES * NUM_MMA_GROUPS, arrive_count=1
    )
    bars_empty_b = tlx.alloc_barriers(
        num_barriers=NUM_STAGES, arrive_count=NUM_MMA_GROUPS
    )
    bars_full_b = tlx.alloc_barriers(num_barriers=NUM_STAGES, arrive_count=1)

    # Warp specilization
    with tlx.async_tasks():
        # Producer (async load)
        with tlx.async_task("default"):
            pid = tl.program_id(axis=0)
            num_pid_m = tl.cdiv(M, BM)
            num_pid_n = tl.cdiv(N, BN)
            num_pid_in_group = GROUP_SIZE_M * num_pid_n
            group_id = pid // num_pid_in_group
            first_pid_m = group_id * GROUP_SIZE_M
            group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
            pid_m = first_pid_m + (pid % group_size_m)
            pid_n = (pid % num_pid_in_group) // group_size_m
            offset_am = pid_m * BM
            offset_bn = pid_n * BN

            # Assuming NUM_STAGES = 2
            # p should be 1, 1, 0, 0, 1, 1, 0, 0, ...
            p = 1

            for k in range(0, tl.cdiv(K, BK)):
                buf = k % NUM_STAGES
                offset_k = k * BK

                # Async load to a[buf]
                empty_a_1st = tlx.local_view(bars_empty_a, buf)  # mbar
                full_a_1st = tlx.local_view(bars_full_a, buf)  # mbar
                tlx.barrier_wait(bar=empty_a_1st, phase=p)  # EmptyBar A1 wait
                tlx.barrier_expect_bytes(
                    full_a_1st, BLOCK_M_SPLIT * BK * tlx.size_of(tlx.dtype_of(a_desc))
                )
                data_a_1st = tlx.local_view(a, buf)  # smem data
                tlx.async_descriptor_load(
                    a_desc, data_a_1st, [offset_am, offset_k], full_a_1st
                )

                # Async load to b[buf]
                empty_b = tlx.local_view(bars_empty_b, buf)
                full_b = tlx.local_view(bars_full_b, buf)
                tlx.barrier_wait(bar=empty_b, phase=p)
                tlx.barrier_expect_bytes(
                    full_b, BN * BK * tlx.size_of(tlx.dtype_of(a_desc))
                )
                data_b = tlx.local_view(b, buf)
                tlx.async_descriptor_load(b_desc, data_b, [offset_k, offset_bn], full_b)

                # Async load to a[buf+NUM_STAGES]
                empty_a_2nd = tlx.local_view(bars_empty_a, buf + NUM_STAGES)
                full_a_2nd = tlx.local_view(bars_full_a, buf + NUM_STAGES)
                tlx.barrier_wait(bar=empty_a_2nd, phase=p)
                tlx.barrier_expect_bytes(
                    bar=full_a_2nd,
                    size=BLOCK_M_SPLIT * BK * tlx.size_of(tlx.dtype_of(a_desc)),
                )
                data_a_2nd = tlx.local_view(a, buf + NUM_STAGES)  # smem data
                tlx.async_descriptor_load(
                    a_desc,
                    data_a_2nd,
                    [offset_am + BLOCK_M_SPLIT, offset_k],
                    full_a_2nd,
                )

                # Flip phase after every NUM_STAGES iterations finish
                p = p ^ (buf == (NUM_STAGES - 1))

        # consumers (wgmma + async store)
        with tlx.async_task(num_warps=4, replicate=2):
            pid = tl.program_id(axis=0)
            num_pid_m = tl.cdiv(M, BM)
            num_pid_n = tl.cdiv(N, BN)
            num_pid_in_group = GROUP_SIZE_M * num_pid_n
            group_id = pid // num_pid_in_group
            first_pid_m = group_id * GROUP_SIZE_M
            group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
            pid_m = first_pid_m + (pid % group_size_m)
            pid_n = (pid % num_pid_in_group) // group_size_m
            offset_am = pid_m * BM
            offset_bn = pid_n * BN

            p = 0
            # Assuming NUM_STAGES = 2
            # p should be 0, 0, 1, 1, 0, 0, ...
            acc = tl.zeros([BM // 2, BN], dtype=tl.float32)
            for k in range(0, tl.cdiv(K, BK)):
                buf = k % NUM_STAGES

                # Wait for TMA load
                full_a = tlx.local_view(
                    bars_full_a, buf + NUM_STAGES * tlx.async_task_replica_id()
                )
                full_b = tlx.local_view(bars_full_b, buf)
                tlx.barrier_wait(bar=full_a, phase=p)
                tlx.barrier_wait(bar=full_b, phase=p)

                # async_dot
                data_a = tlx.local_view(
                    a, buf + NUM_STAGES * tlx.async_task_replica_id()
                )
                data_b = tlx.local_view(b, buf)
                acc = tlx.async_dot(
                    data_a,
                    data_b,
                    acc,
                )
                # async_wait
                acc = tlx.async_dot_wait(tl.constexpr(0), acc)

                # Release buffers
                empty_a = tlx.local_view(
                    bars_empty_a, buf + NUM_STAGES * tlx.async_task_replica_id()
                )
                empty_b = tlx.local_view(bars_empty_b, buf)
                tlx.barrier_arrive(empty_a)  # EmptyBar A1 arrive
                # tlx.barrier_arrive(empty_b)

                # Flip phase after every NUM_STAGES iterations finish
                p = p ^ (buf == (NUM_STAGES - 1))

            offset_cm = offset_am + BLOCK_M_SPLIT * tlx.async_task_replica_id()
            if EPILOGUE_SUBTILE:
                acc = tl.reshape(acc, (BLOCK_M_SPLIT, 2, BN // 2))
                acc = tl.permute(acc, (0, 2, 1))
                acc0, acc1 = tl.split(acc)
                c0 = acc0.to(tlx.dtype_of(c_desc))
                c_desc.store([offset_cm, offset_bn], c0)
                c1 = acc1.to(tlx.dtype_of(c_desc))
                c_desc.store([offset_cm, offset_bn + BN // 2], c1)
            else:
                c_desc.store([offset_cm, offset_bn], acc.to(tlx.dtype_of(c_desc)))


def launch_kernel():
    # --- Scalar parameters (from extracted_args) ---
    M, N, K = 65536, 1024, 1024
    BM, BN, BK = 128, 256, 64
    GROUP_SIZE_M = 8
    NUM_STAGES = 4
    NUM_MMA_WARPS = 8
    NUM_MMA_GROUPS = 2
    EPILOGUE_SUBTILE = True
    BLOCK_M_SPLIT = BM // NUM_MMA_GROUPS  # 64

    grid = (2048,)

    # --- Create tensors with original statistical properties ---
    # a: [65536, 1024] fp16, mean=0.000977, std=0.000977, range=[-0.00456, 0.00639]
    a = (
        torch.randn(M, K, dtype=torch.float32, device="cuda:0") * 0.0009765945142135024
        + 0.00097661092877388
    )
    a = torch.clamp(a, min=-0.0045623779296875, max=0.006389617919921875).to(
        torch.float16
    )

    # b: [1024, 1024] fp16, mean=0.000977, std=0.000976, range=[-0.00387, 0.00561]
    b = (
        torch.randn(K, N, dtype=torch.float32, device="cuda:0") * 0.0009764193091541529
        + 0.0009768697200343013
    )
    b = torch.clamp(b, min=-0.00386810302734375, max=0.00560760498046875).to(
        torch.float16
    )

    # c: [65536, 1024] fp16, all zeros (output buffer)
    c = torch.zeros(M, N, dtype=torch.float16, device="cuda:0")

    # --- Create TensorDescriptors ---
    # Initial block_shape is a dummy; we set the correct values below
    # (mimicking the pre_hook matmul_tma_set_block_size_hook from the original autotune config)
    a_desc = TensorDescriptor(
        a, shape=[M, K], strides=[K, 1], block_shape=[1, 1], padding="zero"
    )
    b_desc = TensorDescriptor(
        b, shape=[K, N], strides=[N, 1], block_shape=[1, 1], padding="zero"
    )
    c_desc = TensorDescriptor(
        c, shape=[M, N], strides=[N, 1], block_shape=[1, 1], padding="zero"
    )

    # Apply the pre_hook logic: set correct TMA block shapes
    a_desc.block_shape = [BLOCK_M_SPLIT, BK]  # [64, 64]
    b_desc.block_shape = [BK, BN]  # [64, 256]
    c_desc.block_shape = [BLOCK_M_SPLIT, BN // 2]  # [64, 128] (EPILOGUE_SUBTILE=True)

    # --- Launch kernel ---
    matmul_kernel_tlx_ws[grid](
        a_desc,
        b_desc,
        c_desc,
        M,
        N,
        K,
        BM,
        BN,
        BK,
        GROUP_SIZE_M,
        NUM_STAGES,
        NUM_MMA_WARPS,
        NUM_MMA_GROUPS,
        EPILOGUE_SUBTILE,
        num_warps=4,
        num_stages=1,
        num_ctas=1,
    )

    torch.cuda.synchronize()
    print("Kernel execution finished.")


if __name__ == "__main__":
    launch_kernel()
